# Generated by Django 4.2.19 on 2025-03-18 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('task_text', models.TextField(verbose_name='任务内容')),
                ('task_status', models.IntegerField(choices=[(1, '已领取'), (0, '已发布'), (2, '已完成')], default=0, verbose_name='任务状态')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='任务用户')),
                ('user_pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_pet')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
            },
        ),
    ]
