# Generated by Django 4.2.19 on 2025-03-19 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_address',
            field=models.TextField(blank=True, null=True, verbose_name='任务地点'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_reward',
            field=models.IntegerField(blank=True, null=True, verbose_name='任务赏金'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.IntegerField(choices=[(1, '已被领取,任务正在进行中'), (2, '已完成任务,祝您生活愉快'), (0, '已发布任务,暂时未被领取')], default=0, verbose_name='任务状态'),
        ),
    ]
